# Generated by Django 4.2.9 on 2024-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_aichat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
