# Generated by Django 4.2.9 on 2024-01-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_aichat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='belongs_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
